[ColorScheme]
active_colors=#191d11, #f7fbe7, #ecf0dc, #747969, #e0e5d1, #c4c9b6, #191d11, #ffffff, #191d11, #f7fbe7, #f7fbe7, #000000, #456800, #ffffff, #4d6544, #4d6544, #f1f6e2, #f7fbe7, #f7fbe7, #44493a, #44493a
disabled_colors=#44493a, #e0e5d1, #ecf0dc, #747969, #e0e5d1, #c4c9b6, #44493a, #44493a, #44493a, #e0e5d1, #e0e5d1, #000000, #e0e5d1, #44493a, #44493a, #44493a, #e0e5d1, #e0e5d1, #e0e5d1, #44493a, #44493a
inactive_colors=#44493a, #f7fbe7, #ecf0dc, #747969, #e0e5d1, #c4c9b6, #44493a, #44493a, #44493a, #f7fbe7, #f7fbe7, #000000, #4d6544, #ffffff, #4d6544, #4d6544, #f1f6e2, #f7fbe7, #f7fbe7, #44493a, #44493a

[ColorEffects:Disabled]
Color=68,73,58
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=116,121,105
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=236,240,220
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Complementary]
BackgroundAlternate=236,240,220
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Header]
BackgroundAlternate=247,251,231
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Header][Inactive]
BackgroundAlternate=247,251,231
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Selection]
BackgroundAlternate=169,249,0
BackgroundNormal=69,104,0
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=255,255,255
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=255,255,255
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Tooltip]
BackgroundAlternate=247,251,231
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:View]
BackgroundAlternate=241,246,226
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[Colors:Window]
BackgroundAlternate=247,251,231
BackgroundNormal=247,251,231
DecorationFocus=69,104,0
DecorationHover=69,104,0
ForegroundActive=69,104,0
ForegroundInactive=68,73,58
ForegroundLink=56,104,70
ForegroundNegative=186,26,26
ForegroundNeutral=77,101,68
ForegroundNormal=25,29,17
ForegroundPositive=56,104,70
ForegroundVisited=77,101,68

[WM]
activeBackground=247,251,231
activeBlend=25,29,17
activeForeground=25,29,17
inactiveBackground=247,251,231
inactiveBlend=68,73,58
inactiveForeground=68,73,58
